In [8]:
import numpy as np

# Two transformation matrices
A = np.array([          #---------> 90-degree rotation
    [0, -1],
    [1,  0]
])  

B = np.array([          #----------> stretch x-axis by 2
    [2, 0],
    [0, 1]
])  

# A point to transform
v = np.array([1, 1])


# Method 1: combined matrix (A@B) applied to v
combined = A @ B
result_combined = combined @ v


# Method 2: apply B first, then A
step1 = B @ v          #-----------> B's transform on v
step2 = A @ step1       #----------> then A's transform on the result

print("v =", v)
print("A =\n", A)
print("B =\n", B)
print("A @ B =\n", combined)
print()
print("Method 1 -- (A@B) @ v =", result_combined)
print("Method 2 -- A @ (B @ v) =", step2)
print("Match:", np.allclose(result_combined, step2))

v = [1 1]
A =
 [[ 0 -1]
 [ 1  0]]
B =
 [[2 0]
 [0 1]]
A @ B =
 [[ 0 -1]
 [ 2  0]]

Method 1 -- (A@B) @ v = [-1  2]
Method 2 -- A @ (B @ v) = [-1  2]
Match: True
